### ISSUE TITLE
Error: Dynamic require of "path" is not supported

### ISSUE THREAD

**Issue by mikecann** [fullstack-build/tslog#119]
**Describe the bug**
Im trying to use this awesome looking lib with esbuild targeting cloudflare workers and I am getting the following error:

```
[mf:err] Error: Dynamic require of "path" is not supported
    at __require (C:\dev\me\tinkering-with-durable-objects\packages\server\dist\index.mjs:28:9)
    at ../../node_modules/source-map-support/source-map-support.js (C:\dev\me\tinkering-with-durable-objects\packages\server\dist\index.mjs:
1812:16)
    at __require2 (C:\dev\me\tinkering-with-durable-objects\packages\server\dist\index.mjs:31:44)
    at ../../node_modules/tslog/dist/cjs/Logger.js (C:\dev\me\tinkering-with-durable-objects\packages\server\dist\index.mjs:2917:32)
    at __require2 (C:\dev\me\tinkering-with-durable-objects\packages\server\dist\index.mjs:31:44)
    at ../../node_modules/tslog/dist/cjs/index.js (C:\dev\me\tinkering-with-durable-objects\packages\server\dist\index.mjs:2935:20)
    at __require2 (C:\dev\me\tinkering-with-durable-objects\packages\server\dist\index.mjs:31:44)
    at C:\dev\me\tinkering-with-durable-objects\packages\server\dist\index.mjs:4604:31
    at SourceTextModule.evaluate (internal/vm/module.js:225:23)
    at ModuleScriptInstance.run (C:\dev\me\tinkering-with-durable-objects\node_modules\miniflare\src\scripts.ts:66:23)
```

Clicking the link in the stack trace takes me to:

```js
// ../../node_modules/tslog/dist/cjs/Logger.js
var require_Logger = __commonJS({
  "../../node_modules/tslog/dist/cjs/Logger.js"(exports) {
    "use strict";
    Object.defineProperty(exports, "__esModule", { value: true });
    exports.Logger = void 0;
    var source_map_support_1 = require_source_map_support();
    var LoggerWithoutCallSite_1 = require_LoggerWithoutCallSite();
    var Logger2 = class extends LoggerWithoutCallSite_1.LoggerWithoutCallSite {
      constructor(settings, parentSettings) {
        super(settings, parentSettings);
        this._callSiteWrapper = source_map_support_1.wrapCallSite;
      }
    };
    exports.Logger = Logger2;
  }
});
```

It looks like the culprit is `require_source_map_support()`. Im not sure if cloudflare workers have some sort of special requirements or whatnot or if its esbuild that is stripping something out. 

Any ideas?

**Comment by denosaurtrain** [comment]
I ran into the same error but no cloudflare in my case. I found a workaround for local development that displays source information with esm+tslog+esbuild+typescript: `npx esbuild src/index.ts --bundle --platform=node --outdir=dist --sourcemap=inline --sources-content=false --format=esm --external:source-map-support --out-extension:.js=.mjs --main-fields=module`.

Although that worked, I then ran into https://github.com/fullstack-build/tslog/issues/99 and decided to abandon the esm output format, allowing me to remove the workaround: `npx esbuild src/index.ts --bundle --platform=node --outdir=dist --sourcemap=inline --sources-content=false`.

**Comment by terehov** [comment]
Not quite. Looks like a problem with CJS. 
V4 is going to be a huge rewrite and ESM first. I hope it would fix that.

**Comment by terehov** [comment]
There is a new `next` release of version 4.0. It is ESM only. Could you give it a go and see if it helps? I would appreciate your feedback. 

- `npm i tslog@next`

- and run it with `node --enable-source-maps` or for TypeScript `node --enable-source-maps --experimental-specifier-resolution=node --no-warnings --loader ts-node/esm`

**Comment by terehov** [comment]
Well spotted, thank you. 
Can you please try this one: 

```
npm i tslog@4.0.0-2
```

**Comment by terehov** [comment]
That's because the API has changed. 
I have updated the documentation: [tslog.js.org](https://tslog.js.org)

V4 is released now, so I'm going to close this issue. 
If you shouldn't be able to find the solution, I would be happy to help.
