### ISSUE TITLE
Bug: [BUG] Suspected bug in infinite loop avoidance logic

### ISSUE THREAD

**Issue by cspotcode** [fullstack-build/tslog#139]
**Describe the bug**

Someone reported this bug a while back:
https://github.com/cspotcode/node-source-map-support/issues/36

I see that tslog has logic to avoid infinite loops.  This suggests to me that the logic might be failing in certain situations.

https://github.com/fullstack-build/tslog/blob/3b47ff2036a6e4b05eb07a64d8d0d9b7d7f48bd9/src/CallSitesHelper.ts#L42-L49

**To Reproduce**

Ping @GhaithZamrik for a proper reproduction, and for all of the following details.

**Expected behavior**

**Screenshots**

**Additional context**

**Node.js Version**

**OS incl. Version**

Windows; @GhaithZamrik says it only happens on windows.

**Comment by GhaithZamrik** [comment]
I can't say what are the reproducible steps per se as there's nothing special about the project. If I am able to create a simpler version that causes the same issue I'll post it here. It's a TS NextJS project. 

The information that I have at the moment are the following: 

Error: 
`
C:\Users\user\repo\node_modules\@cspotcode\source-map-support\source-map-support.js:227
  while (match = re.exec(fileData)) lastMatch = match;
                    ^
RangeError: Maximum call stack size exceeded
    at RegExp.exec (<anonymous>)
    at retrieveSourceMapURL (C:\Users\user\repo\node_modules\@cspotcode\source-map-support\source-map-support.js:227:21)
    at Array.<anonymous> (C:\Users\user\repo\node_modules\@cspotcode\source-map-support\source-map-support.js:239:26)
    at C:\Users\user\repo\node_modules\@cspotcode\source-map-support\source-map-support.js:138:32
    at mapSourcePosition (C:\Users\user\repo\node_modules\@cspotcode\source-map-support\source-map-support.js:269:21)
    at wrapCallSite (C:\Users\user\repo\node_modules\@cspotcode\source-map-support\source-map-support.js:461:20)
    at prepareStackTrace (C:\Users\user\repo\node_modules\@cspotcode\source-map-support\source-map-support.js:541:41)
    at Function.prepareStackTrace (C:\Users\user\repo\node_modules\tslog\src\CallSitesHelper.ts:59:31)
    at maybeOverridePrepareStackTrace (node:internal/errors:141:29)
    at prepareStackTrace (node:internal/errors:115:5)
error Command failed with exit code 1.
`

OS: Windows 10 Pro version 21H2
it only happens on Windows and Linux subsystem for windows, I wasn't able to replicate on Mac OS or a native Linux machine. 

It mostly happens when using node 16. I haven't observed the issue when rolling back to 14

**Comment by GhaithZamrik** [comment]
@cspotcode Yes, I understand that...

As I said I will share something when I have an example that I can share and reproduces the issue :)

**Comment by terehov** [comment]
Thank you, @cspotcode for pointing that out. 

@GhaithZamrik, have you been able to extract a minimal example? I would appreciate it a lot.

**Comment by terehov** [comment]
I've been working on a new, completely rewritten version (4.0), which does not use this logic anymore. Can you give it a go and let me know if that solves your problem?

- `npm i tslog@next`

- and run it with `node --enable-source-maps` or for TypeScript `node --enable-source-maps --experimental-specifier-resolution=node --no-warnings --loader ts-node/esm`

Thank you.

**Comment by terehov** [comment]
V4 is released now, so I'm going to close this issue. 
Feel free to open a new one if V4 didn't solve it for you. 

Here are the docs: [tslog.js.org](https://tslog.js.org)

**Comment by cai-zhuo** [comment]
I met this issue again with **node version: v16.18.0**  **@cspotcode/source-map-support: 0.8.1** 
I didn't find **tslog** in my pnpm-lock.yaml 
------------------------------------------------------------------------------------------------------------------
RangeError: Maximum call stack size exceeded
    at RegExp.exec (<anonymous>)
    at retrieveSourceMapURL (/Users/bytedance/Workspace/livesaas-client/.eden-mono/temp/node_modules/.pnpm/@cspotcode+source-map-support@0.8.1/node_modules/@cspotcode/source-map-support/source-map-support.js:340:21)
    at Array.<anonymous> (/Users/bytedance/Workspace/livesaas-client/.eden-mono/temp/node_modules/.pnpm/@cspotcode+source-map-support@0.8.1/node_modules/@cspotcode/source-map-support/source-map-support.js:353:26)
    at /Users/bytedance/Workspace/livesaas-client/.eden-mono/temp/node_modules/.pnpm/@cspotcode+source-map-support@0.8.1/node_modules/@cspotcode/source-map-support/source-map-support.js:199:32
    at mapSourcePosition (/Users/bytedance/Workspace/livesaas-client/.eden-mono/temp/node_modules/.pnpm/@cspotcode+source-map-support@0.8.1/node_modules/@cspotcode/source-map-support/source-map-support.js:383:21)
    at wrapCallSite (/Users/bytedance/Workspace/livesaas-client/.eden-mono/temp/node_modules/.pnpm/@cspotcode+source-map-support@0.8.1/node_modules/@cspotcode/source-map-support/source-map-support.js:592:20)
    at Function.prepareStackTrace (/Users/bytedance/Workspace/livesaas-client/.eden-mono/temp/node_modules/.pnpm/@cspotcode+source-map-support@0.8.1/node_modules/@cspotcode/source-map-support/source-map-support.js:671:41)
    at maybeOverridePrepareStackTrace (node:internal/errors:141:29)
    at prepareStackTrace (node:internal/errors:115:5)
    at /Users/bytedance/Workspace/livesaas-client/.eden-mono/temp/node_modules/.pnpm/@volcengine+rtc@4.47.1/node_modules/@volcengine/rtc/index.min.js:6:47502
    at /Users/bytedance/Workspace/livesaas-client/.eden-mono/temp/node_modules/.pnpm/@volcengine+rtc@4.47.1/node_modules/@volcengine/rtc/index.min.js:6:84
    at Object.<anonymous> (/Users/bytedance/Workspace/livesaas-client/.eden-mono/temp/node_modules/.pnpm/@volcengine+rtc@4.47.1/node_modules/@volcengine/rtc/index.min.js:6:200)
    at Module._compile (node:internal/modules/cjs/loader:1155:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
    at Object.require.extensions.<computed> [as .js] (/Users/bytedance/Workspace/livesaas-client/.eden-mono/temp/node_modules/.pnpm/ts-node@10.9.1_b6b77fb7f9ad71c4cc5109308e4dc9fa/node_modules/ts-node/src/index.ts:1608:43)
    at Module.load (node:internal/modules/cjs/loader:1033:32)

**Comment by terehov** [comment]
It does not seem to be tslog related. In fact, this library is not even used by tslog anymore and tslog is dependency free. Please open an issue with the library causing this problem (source-map-support).

**Comment by cai-zhuo** [comment]
> It does not seem to be tslog related. In fact, this library is not even used by tslog anymore and tslog is dependency free. Please open an issue with the library causing this problem (source-map-support).

ok thanks
