### ISSUE TITLE
Bug: [BUG] logging undefined as a value for an object causes a unhandled exception

### ISSUE THREAD

**Issue by auberryberry** [fullstack-build/tslog#186]
Logging an object with a field named anything and a value of undefined causes the library to fall over.
```{ test: undefined }``` <-logging this as the message or value is enough to kill tslog.

```
util.inspect.polyfil.js:45 Uncaught TypeError: Cannot read properties of undefined (reading '0')
    at Object.stylizeWithColor [as stylize] (util.inspect.polyfil.js:45:1)
    at formatPrimitive (util.inspect.polyfil.js:280:1)
    at formatValue (util.inspect.polyfil.js:120:1)
    at formatProperty (util.inspect.polyfil.js:232:1)
    at util.inspect.polyfil.js:189:1
    at Array.map (<anonymous>)
    at formatValue (util.inspect.polyfil.js:188:1)
    at inspect (util.inspect.polyfil.js:20:1)
    at index.js:128:1
    at Array.map (<anonymous>)
```

**Comment by terehov** [comment]
Thanks. Looks like it’s inside the inspect polifil. I’ll fix it soon.

**Comment by auberryberry** [comment]
Amazing, thank you for the quick fix, as usual.
