### ISSUE TITLE
Bug: [BUG] Crashes on undefined if maskValuesRegEx option specified

### ISSUE THREAD

**Issue by ekho** [fullstack-build/tslog#197]
**Describe the bug**
Crashes on `undefined` if `maskValuesRegEx` option specified

**To Reproduce**

```typescript
import { Logger } from 'tslog';

const logger = new Logger({ maskValuesRegEx: [/bearer \S+/] });

logger.info(undefined);
```

**Expected behavior**
Log empty value same as in case without `maskValuesRegEx`.

**Screenshots**
```
> node dist/cli
./node_modules/tslog/dist/cjs/BaseLogger.js:181
                                    source = source.replace(regEx, this.settings.maskPlaceholder);
                                                    ^

TypeError: Cannot read properties of undefined (reading 'replace')
    at ./node_modules/tslog/dist/cjs/BaseLogger.js:181:53
    at Array.forEach (<anonymous>)
    at ./node_modules/tslog/dist/cjs/BaseLogger.js:180:65
    at Logger._recursiveCloneAndMaskValuesOfKeys (./node_modules/tslog/dist/cjs/BaseLogger.js:184:31)
    at ./node_modules/tslog/dist/cjs/BaseLogger.js:154:25
    at Array.map (<anonymous>)
    at Logger._mask (./node_modules/tslog/dist/cjs/BaseLogger.js:153:22)
    at Logger.log (./node_modules/tslog/dist/cjs/BaseLogger.js:96:24)
    at Logger.info (./node_modules/tslog/dist/cjs/index.js:23:22)
    at Object.<anonymous> (./src/cli.ts:35:8)
```

**Additional context**

**Node.js Version**
Node.js v18.12.1

**OS incl. Version**
macOS 13.1 (22C65)

**Comment by terehov** [comment]
Thank you. I’ll fix it today

**Comment by ekho** [comment]
@terehov thank you!

**Comment by terehov** [comment]
V4.4.6 is out now 👍

**Comment by ekho** [comment]
Amazing )

**Comment by ekho** [comment]
@terehov yet another problem

```
import { Logger } from 'tslog';

const logger = new Logger({ maskValuesRegEx: [/bearer \S+/] });

logger.info({ count: 0 });
```

```
TypeError: source?.replace is not a function

./node_modules/tslog/dist/cjs/BaseLogger.js:181
                                    source = source?.replace(regEx, this.settings.maskPlaceholder);
```

**Comment by terehov** [comment]
Ok, looks like a lack of tests. I'll add some tests and fix it. Thank you 👍

**Comment by terehov** [comment]
I'll fix the other issues tomorrow and release a new version afterwards.

**Comment by terehov** [comment]
V4.6.0 is out that fixes this and adds more tests.
