### ISSUE TITLE
Bug: Passing Buffer object causes an error

### ISSUE THREAD

**Issue by whitphx** [fullstack-build/tslog#86]
**Describe the bug**

Version: 3.1.0

When a `Buffer` object is passed to logging methods, an error occurs.

**To Reproduce**

Run the code below:
```typescript
import { Logger } from 'tslog'
const logger = new Logger()
const buffer = Buffer.from('foo')
logger.info(buffer)
```

Then, an error as below is thrown.
```
/srv # yarn ts-node reproduce-error.ts
yarn run v1.22.5
$ /srv/node_modules/.bin/ts-node reproduce-error.ts
2021-02-01 06:28:15.593  INFO [reproduce-error.ts:4 Object.<anonymous>] TypeError: Method get TypedArray.prototype.length called on incompatible receiver [object Object]
    at Buffer.get length [as length] (<anonymous>)
    at Buffer.inspect (buffer.js:826:39)
    at internal/per_context/primordials.js:23:32
    at formatValue (internal/util/inspect.js:764:19)
    at Object.inspect (internal/util/inspect.js:326:10)
    at Logger._inspectAndHideSensitive (/srv/node_modules/tslog/src/LoggerWithoutCallSite.ts:885:26)
    at /srv/node_modules/tslog/src/LoggerWithoutCallSite.ts:652:18
    at Array.forEach (<anonymous>)
    at Logger.printPrettyLog (/srv/node_modules/tslog/src/LoggerWithoutCallSite.ts:632:30)
    at Logger._handleLog (/srv/node_modules/tslog/src/LoggerWithoutCallSite.ts:348:14)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Expected behavior**

I think a log similar to the output from `console.log` should be printed as below.
```
<Buffer 66 6f 6f>
```

**Node.js Version**
v14.13.1

**OS incl. Version**
Alpine Linux (`node:14-alpine` docker image)

**Comment by terehov** [comment]
Thank you very much. I have this issue on my agenda already and working on a new release targeting all 3 open issues, which I am going to release soon!

**Comment by whitphx** [comment]
Awesome! Thank you very much

**Comment by terehov** [comment]
Here you go :-)

https://github.com/fullstack-build/tslog/releases/tag/v3.1.1

**Comment by whitphx** [comment]
Wow thank you for the quick fix!
